version: '2'
services:
  api:
    image: tetra-api
    container_name: tetra-api
    depends_on:
      - db
    links:
      - db
    command: |
      bash -c "export PYTHONUNBUFFERED=1 && gunicorn --reload -t 120 --bind 0.0.0.0:7374 --access-logfile - tetra.app:application"
    labels:
      - "traefik.enable=true"
      # password hashed according to https://docs.traefik.io/middlewares/basicauth/#general
      # so: `htpasswd -nb -B <username> <password>` and escaped `$` signs (as `$$`)
      - "traefik.http.middlewares.auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api/"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.middlewares=api-stripprefix,auth"
      - "traefik.http.services.backend.loadbalancer.server.port=7374"
  worker:
    image: tetra-api
    container_name: tetra-worker
    depends_on:
      - queue
    links:
      - queue
    # celery has a `--auotreload` flag that doesn't reload dependent modules,
    # so it doesn't work. use `docker-compose restart worker` instead.
    command: |
      su -m tetra-worker -c "celery --app=tetra.worker.app worker --loglevel=INFO"
  db:
    image: postgres:9.5
    container_name: tetra-db
    ports:
      # note: exposing port 5432 here causes issues in travis builds
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tetra-db
  queue:
    image: rabbitmq:3.6-management
    container_name: tetra-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: tetra
      RABBITMQ_DEFAULT_PASS: password
  ui:
    image: tetra-ui
    container_name: tetra-ui
    depends_on:
      - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.middlewares=auth"
  gateway:
    image: traefik:v2.0
    container_name: tetra-gateway
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - ui
      - api