FROM node:18-alpine
WORKDIR /work
ENV NODE_ENV development
COPY package.json package-lock.json ./
COPY . ./
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG GITLAB_TOKEN
ENV PORT=80
EXPOSE 80
CMD npm run autobuild
